### ISSUE TITLE
Thirdpersoncontroller is a type not a namespace error

### ISSUE THREAD

**Issue by ah3243** [rico345100/unity-footstep-example#1]
hi thanks for making this. I'm getting an error when i try and load it though. Do you have any requirements of unity version or other packages ect?

Here are the two errors I'm getting

Assets/Scripts/FootstepSwapper.cs(4,7): error CS0138: A 'using namespace' directive can only be applied to namespaces; 'ThirdPersonController' is a type not a namespace. Consider a 'using static' directive instead

Assets/Scripts/FootstepSwapper.cs(11,13): error CS0246: The type or namespace name 'ThirdPersonController' could not be found (are you missing a using directive or an assembly reference?)

**Comment by rico345100** [comment]
Use the correct version of Unity. It's been years, and lots of things changed internally.
